name: Semgrep Full Scan
on:
  workflow_dispatch:

jobs:
  semgrep-full:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: Clone application source code
        uses: actions/checkout@v3

      - name: Run full Semgrep scan
        run: |
          semgrep \
            --output report.log \
            --config p/default

      - name: Upload Semgrep report
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-report
          path: report.log
